services:

 web:
  build: ./
  restart: always
  ports:
   - 8080:8080

 db:
  build: ./db
  restart: always
  environment:
   MARIADB_ROOT_PASSWORD: mypass
  volumes:
   - /home/oleg/mariaDb:/var/lib/mysql
  ports:
   - 3306:3306

